"""update venue seeking migration.

Revision ID: 8474e7550b29
Revises: 88122e6b7201
Create Date: 2020-04-07 12:26:01.940701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8474e7550b29'
down_revision = '88122e6b7201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.drop_constraint(u'Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'], ondelete='cascade')
    op.drop_constraint(u'Venue_Seeking_artist_id_fkey', 'Venue_Seeking', type_='foreignkey')
    op.create_foreign_key(None, 'Venue_Seeking', 'Artist', ['artist_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue_Seeking', type_='foreignkey')
    op.create_foreign_key(u'Venue_Seeking_artist_id_fkey', 'Venue_Seeking', 'Venue_Seeking', ['artist_id'], ['id'], ondelete=u'CASCADE')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key(u'Show_artist_id_fkey', 'Show', 'Venue_Seeking', ['artist_id'], ['id'], ondelete=u'CASCADE')
    op.create_foreign_key(u'Show_venue_id_fkey', 'Show', 'Venue_Seeking', ['venue_id'], ['id'], ondelete=u'CASCADE')
    # ### end Alembic commands ###
