"""add new models migration.

Revision ID: 88122e6b7201
Revises: 6d20c279f5aa
Create Date: 2020-04-06 18:47:31.037013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88122e6b7201'
down_revision = '6d20c279f5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Venue_Seeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Venue_Seeking.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Artist_Genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.create_table('Talent_Seeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue_Genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    op.drop_table('TalentSeeking')
    op.drop_table('VenueSeeking')
    op.add_column(u'Address', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Address', 'City', ['city_id'], ['id'], ondelete='cascade')
    op.add_column(u'Artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'City', ['city_id'], ['id'])
    op.drop_column(u'Artist', 'city')
    op.drop_column(u'Artist', 'genres')
    op.drop_column(u'Artist', 'state')
    op.add_column(u'City', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'City', 'State', ['state_id'], ['id'], ondelete='cascade')
    op.add_column(u'Show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column(u'Show', sa.Column('start_time', sa.Date(), nullable=True))
    op.add_column(u'Show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Show', 'Venue_Seeking', ['venue_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'Show', 'Venue_Seeking', ['artist_id'], ['id'], ondelete='cascade')
    op.drop_column(u'Show', 'name')
    op.add_column(u'Venue', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Address', ['address_id'], ['id'])
    op.drop_column(u'Venue', 'city')
    op.drop_column(u'Venue', 'state')
    op.drop_column(u'Venue', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column(u'Venue', 'address_id')
    op.add_column(u'Show', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column(u'Show', 'venue_id')
    op.drop_column(u'Show', 'start_time')
    op.drop_column(u'Show', 'artist_id')
    op.drop_constraint(None, 'City', type_='foreignkey')
    op.drop_column(u'City', 'state_id')
    op.add_column(u'Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column(u'Artist', 'city_id')
    op.drop_constraint(None, 'Address', type_='foreignkey')
    op.drop_column(u'Address', 'city_id')
    op.create_table('VenueSeeking',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"VenueSeeking_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'VenueSeeking_pkey')
    )
    op.create_table('TalentSeeking',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"TalentSeeking_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'TalentSeeking_pkey')
    )
    op.drop_table('Venue_Genres')
    op.drop_table('Talent_Seeking')
    op.drop_table('Artist_Genres')
    op.drop_table('Venue_Seeking')
    # ### end Alembic commands ###
